version: "3"
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: point-prism
      MYSQL_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - pp-db:/var/lib/mysql
volumes:
  pp-db:
